# Generated by Django 4.1.1 on 2022-09-27 08:13

from django.db import migrations, models
import logging


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0002_rename_ask_post_eventattention_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(verbose_name=logging.PlaceHolder),
        ),
        migrations.AlterField(
            model_name='post',
            name='eventAttention',
            field=models.TextField(default='솜솜이들에게 전하고 싶은 한줄'),
        ),
    ]
