# Generated by Django 4.1.1 on 2022-09-27 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0003_alter_comment_comment_alter_post_eventattention'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='eventAttention',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='eventTitle',
            field=models.TextField(),
        ),
    ]
