# Generated by Django 4.1.1 on 2022-09-27 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='post_photo')),
                ('title', models.CharField(max_length=14)),
                ('introduction', models.TextField()),
                ('info', models.TextField()),
                ('note', models.TextField()),
                ('ask', models.TextField()),
            ],
        ),
    ]
