# Generated by Django 4.1.1 on 2022-09-27 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='ask',
            new_name='eventAttention',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='info',
            new_name='eventGuide',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='poster',
            new_name='eventImg',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='introduction',
            new_name='eventIntro',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='eventTitle',
        ),
        migrations.RemoveField(
            model_name='post',
            name='note',
        ),
    ]
